"""默认路径和配置值。"""

from __future__ import annotations

from pathlib import Path

CONFIG_DIR = Path.home() / ".config" / "tradar"
DEFAULT_CONFIG_PATH = CONFIG_DIR / "config.toml"
DEFAULT_DATA_DIR = Path.home() / ".local" / "share" / "tradar"
DEFAULT_STATE_DIR = DEFAULT_DATA_DIR
DEFAULT_OUTPUT_DIR = DEFAULT_DATA_DIR / "runs"
DEFAULT_DAYS_WINDOW = 30
DEFAULT_MAX_PACK_TOKENS = 24000
DEFAULT_MAX_SOURCE_FILE_BYTES = 5 * 1024 * 1024
DEFAULT_AGENT_TIMEOUT_SECONDS = 300
DEFAULT_SCHEMA_REPAIR_TIMEOUT_SECONDS = 300
DEFAULT_HTML_DESIGN_TIMEOUT_SECONDS = 300
DEFAULT_CODEX_BINARY = "codex"
DEFAULT_CLAUDE_BINARY = "claude"
DEFAULT_DEBUG_RETENTION_RUN_COUNT = 20
DEFAULT_LOW_CONFIDENCE_EVIDENCE_THRESHOLD = 3
